# Generated by Django 2.2.4 on 2020-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20200305_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
